require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
-- require "user.cmp"
-- require "user.lsp"
vim.cmd('source $HOME/.config/nvim/lua/user/coc.vim')
require "user.ranger"
require "user.telescope"
require "user.harpoon"
require "user.git-worktree"
require "user.treesitter"
-- require "user.lua-snip"
require "user.fugitive"
require "user.lazygit"
require "user.neoclip"
require "user.lualine"
require "user.git-gutter"
require "user.ultisnips"
